version: '3.8'

services:
  h2:
    image: semoss/h2:1.4.200
    container_name: h2db
    ports:
      - "8082:8082" # Port for H2 web console
      - "9092:9092" # Port for TCP connection
    environment:
      H2_OPTIONS: '-tcp -tcpAllowOthers -web -webAllowOthers'
    volumes:
      - h2-data:/opt/h2-data
    restart: unless-stopped
    networks:
      - h2-net
    env_file:
      - .env

volumes:
  h2-data:

networks:
  h2-net:
    driver: bridge