version: '3.8'

services:
  h2:
    image: semoss/h2:1.4.200
    container_name: h2db
    ports:
      - "8082:8082" # Port for H2 web console
      - "9092:9092" # Port for TCP connection
    environment:
      H2_OPTIONS: '-tcp -tcpAllowOthers -tcpPort 9092 -web -webAllowOthers -webPort 8082'
      H2_USERNAME: ${H2_USERNAME}
      H2_PASSWORD: ${H2_PASSWORD}
      H2_DB_NAME: ${H2_DB_NAME}
    volumes:
      - h2-data:/opt/h2-data
      - ./db/migration/V1__create_schema.sql:/docker-entrypoint-initdb.d/V1__create_schema.sql
      - ./db/migration/V2__create_tables.sql:/docker-entrypoint-initdb.d/V2__create_tables.sql
      - ./db/migration/V3__insert_initial_data.sql:/docker-entrypoint-initdb.d/V3__insert_initial_data.sql
    restart: unless-stopped
    env_file:
      - .env

volumes:
  h2-data: