spring:
  datasource:
    url: jdbc:h2:mem:${H2_DB_NAME};DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: ${H2_USERNAME}
    password: ${H2_PASSWORD}
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  flyway:
    enabled: true
    clean-on-validation-error: true
    create-schemas: true
    schemas: "PUBLIC"