spring:
  datasource:
    url: jdbc:h2:file:./data/${H2_DB_NAME};DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: ${H2_USERNAME}
    password: ${H2_PASSWORD}
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        default_schema: ${H2_DB_SCHEMA}
    hibernate:
      ddl-auto: none
  devtools:
    restart:
      enabled: true
