spring:
  datasource:
    url: jdbc:h2:file:./data/${H2_DB_NAME};DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: ${H2_USERNAME}
    password: ${H2_PASSWORD}
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        default_schema: ${H2_DB_SCHEMA}
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    schemas: ${H2_DB_SCHEMA}
    baseline-on-migrate: true
    locations: classpath:db/migration
    placeholders:
      H2_DB_SCHEMA: ${H2_DB_SCHEMA}
      H2_DB_NAME: ${H2_DB_NAME}
      H2_USERNAME: ${H2_USERNAME}
      H2_PASSWORD: ${H2_PASSWORD}
  devtools:
    restart:
      enabled: true
