CREATE TABLE ${H2_DB_SCHEMA}.board
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE ${H2_DB_SCHEMA}.card_list
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE ${H2_DB_SCHEMA}.card
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255) NOT NULL,
    describe VARCHAR(255)
);

CREATE TABLE ${H2_DB_SCHEMA}.member
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(120) NOT NULL,
    last_name VARCHAR(120) NOT NULL,
    email     VARCHAR(255) NOT NULL,
    phone     VARCHAR(15)  NOT NULL
);

CREATE TABLE ${H2_DB_SCHEMA}.board_card_list
(
    board_id     BIGINT,
    card_list_id BIGINT,
    PRIMARY KEY (board_id, card_list_id),
    FOREIGN KEY (board_id) REFERENCES ${H2_DB_SCHEMA}.board (id) ON DELETE CASCADE,
    FOREIGN KEY (card_list_id) REFERENCES ${H2_DB_SCHEMA}.card_list (id) ON DELETE CASCADE
);

CREATE TABLE ${H2_DB_SCHEMA}.card_list_card
(
    card_list_id BIGINT,
    card_id      BIGINT,
    PRIMARY KEY (card_list_id, card_id),
    FOREIGN KEY (card_list_id) REFERENCES ${H2_DB_SCHEMA}.card_list (id) ON DELETE CASCADE,
    FOREIGN KEY (card_id) REFERENCES ${H2_DB_SCHEMA}.card (id) ON DELETE CASCADE
);

CREATE TABLE ${H2_DB_SCHEMA}.card_member
(
    card_id   BIGINT,
    member_id BIGINT,
    PRIMARY KEY (card_id, member_id),
    FOREIGN KEY (card_id) REFERENCES ${H2_DB_SCHEMA}.card (id) ON DELETE CASCADE,
    FOREIGN KEY (member_id) REFERENCES ${H2_DB_SCHEMA}.member (id) ON DELETE CASCADE
);
