CREATE TABLE ${H2_DB_SCHEMA}.board (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(255) NOT NULL
);

CREATE TABLE ${H2_DB_SCHEMA}.card_list (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           name VARCHAR(255) NOT NULL,
                           board_id BIGINT,
                           CONSTRAINT fk_board
                               FOREIGN KEY (board_id)
                                   REFERENCES ${H2_DB_SCHEMA}.board (id)
                                   ON DELETE CASCADE
);

CREATE TABLE ${H2_DB_SCHEMA}.card (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      text VARCHAR(255) NOT NULL,
                      card_list_id BIGINT,
                      CONSTRAINT fk_card_list
                          FOREIGN KEY (card_list_id)
                              REFERENCES ${H2_DB_SCHEMA}.card_list (id)
                              ON DELETE CASCADE
);