CREATE TABLE ${H2_DB_SCHEMA}.board
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE ${H2_DB_SCHEMA}.card_list
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255) NOT NULL,
    board_id BIGINT,
    CONSTRAINT fk_board
        FOREIGN KEY (board_id)
            REFERENCES ${H2_DB_SCHEMA}.board (id)
            ON DELETE CASCADE
);

CREATE TABLE ${H2_DB_SCHEMA}.card
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    describe     VARCHAR(255),
    card_list_id BIGINT,
    CONSTRAINT fk_card_list
        FOREIGN KEY (card_list_id)
            REFERENCES ${H2_DB_SCHEMA}.card_list (id)
            ON DELETE CASCADE
);

CREATE TABLE ${H2_DB_SCHEMA}.member
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(120) NOT NULL,
    last_name VARCHAR(120) NOT NULL,
    email     VARCHAR(255) NOT NULL,
    phone     VARCHAR(15)  NOT NULL,
    card_id   BIGINT,
    CONSTRAINT fk_card
        FOREIGN KEY (card_id)
            REFERENCES ${H2_DB_SCHEMA}.card (id)
            ON DELETE CASCADE
);