@localServer=http://localhost:8080
@server={{localServer}}
@id=

### Get all cards
GET {{localServer}}/v1/cards
Content-Type: application/json

### Get one card by the particular id
GET {{localServer}}/v1/cards/1
Content-Type: application/json

### Create card
POST {{localServer}}/v1/cards
Content-Type: application/json

{
  "name": "Card 10",
  "describe": "This card is for testing",
  "members": [
    {
      "name": "TestName",
      "lastName": "TestLastName",
      "email": "test.email@exemple.com",
      "phone": "452547878"
    }
  ]
}

### Update card by particular id
PUT {{localServer}}/v1/cards/7
Content-Type: application/json

{
  "describe": "This is first modified card. It contains some information."
}

### Delete card for this particular id
DELETE {{localServer}}/v1/cards/7
Content-Type: application/json