@localServer=http://localhost:8080
@server={{localServer}}
@id=

### Get all cards
GET {{localServer}}/v1/cards
Content-Type: application/json

### Get one card by the particular id
GET {{localServer}}/v1/cards/10
Content-Type: application/json

### Create card
POST {{localServer}}/v1/cards
Content-Type: application/json

{
  "name": "Task 1",
  "describe": "Description for Task 1",
  "members": []
}

### Update card by particular id
PUT {{localServer}}/v1/cards/3
Content-Type: application/json

{
  "name": "Task 1",
  "describe": "Description for Task 1",
  "members": [
    {
      "name": "John",
      "lastName": "Doe",
      "email": "john.doe@example.com",
      "phone": "1234567890"
    },
    {
      "name": "Jane",
      "lastName": "Smith",
      "email": "jane.smith@example.com",
      "phone": "0987654321"
    }
  ]
}

### Delete card for this particular id
DELETE {{localServer}}/v1/cards/7
Content-Type: application/json