@localServer=http://localhost:8080
@server={{localServer}}
@id=

### Get all card list
GET {{localServer}}/v1/card-list
Content-Type: application/json

### Get one card list by the particular id
GET {{localServer}}/v1/card-list/1
Content-Type: application/json

### Create card list
POST {{localServer}}/v1/card-list
Content-Type: application/json

{
  "name": "To Do",
  "cards": []
}

### Update card list by particular id
PUT {{localServer}}/v1/card-list/33
Content-Type: application/json

{
  "name": "To Do",
  "cards": [
    {
      "name": "Task 1",
      "describe": "Description for Task 1",
      "members": [
        {
          "name": "John",
          "lastName": "Doe",
          "email": "john.doe@example.com",
          "phone": "1234567890"
        },
        {
          "name": "Jane",
          "lastName": "Smith",
          "email": "jane.smith@example.com",
          "phone": "0987654321"
        }
      ]
    },
    {
      "name": "Task 2",
      "describe": "Description for Task 2",
      "members": [
        {
          "name": "Alice",
          "lastName": "Johnson",
          "email": "alice.johnson@example.com",
          "phone": "5555555555"
        }
      ]
    }
  ]
}

### Delete card list for this particular id
DELETE {{localServer}}/v1/card-list/7
Content-Type: application/json